"""add anime_catalog table for knowledge base

Revision ID: 5caaed1bcf9b
Revises: ea335ea97dce
Create Date: 2026-03-09 18:56:37.828866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5caaed1bcf9b'
down_revision: Union[str, None] = 'ea335ea97dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_english', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('anime_type', sa.String(length=20), nullable=True),
    sa.Column('anime_status', sa.String(length=30), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('demographics', sa.Text(), nullable=True),
    sa.Column('studios', sa.Text(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mal_score', sa.Float(), nullable=True),
    sa.Column('mal_members', sa.Integer(), nullable=True),
    sa.Column('mal_rank', sa.Integer(), nullable=True),
    sa.Column('mal_popularity', sa.Integer(), nullable=True),
    sa.Column('related_anime_ids', sa.Text(), nullable=True),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_catalog_is_embedded'), 'anime_catalog', ['is_embedded'], unique=False)
    op.create_index(op.f('ix_anime_catalog_mal_id'), 'anime_catalog', ['mal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anime_catalog_mal_id'), table_name='anime_catalog')
    op.drop_index(op.f('ix_anime_catalog_is_embedded'), table_name='anime_catalog')
    op.drop_table('anime_catalog')
    # ### end Alembic commands ###
