"""add_watchlist_status_rating_reaction

Revision ID: c302cb587ee1
Revises: ca36a67feb44
Create Date: 2026-03-15 21:07:11.547717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c302cb587ee1'
down_revision: Union[str, None] = 'ca36a67feb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_entries', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('watchlist_entries', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.add_column('watchlist_entries', sa.Column('reaction', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_entries', 'reaction')
    op.drop_column('watchlist_entries', 'user_rating')
    op.drop_column('watchlist_entries', 'status')
    # ### end Alembic commands ###
