"""add_watchlist_table

Revision ID: ca36a67feb44
Revises: 0ad459705780
Create Date: 2026-03-15 21:00:58.204457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca36a67feb44'
down_revision: Union[str, None] = '0ad459705780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('mal_score', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('anime_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mal_id', name='uq_watchlist_user_anime')
    )
    op.create_index(op.f('ix_watchlist_entries_mal_id'), 'watchlist_entries', ['mal_id'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_user_id'), 'watchlist_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_entries_user_id'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_mal_id'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    # ### end Alembic commands ###
