"""add anime_lists anime_entries and user_preference_profiles tables

Revision ID: ea335ea97dce
Revises: a0ac6f654e34
Create Date: 2026-03-09 17:05:28.397041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea335ea97dce'
down_revision: Union[str, None] = 'a0ac6f654e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mal_username', sa.String(length=255), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_lists_mal_username'), 'anime_lists', ['mal_username'], unique=False)
    op.create_index(op.f('ix_anime_lists_user_id'), 'anime_lists', ['user_id'], unique=True)
    op.create_table('user_preference_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('anime_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preference_profiles_user_id'), 'user_preference_profiles', ['user_id'], unique=True)
    op.create_table('anime_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anime_list_id', sa.String(length=36), nullable=False),
    sa.Column('mal_anime_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_english', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('watch_status', sa.String(length=20), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=False),
    sa.Column('episodes_watched', sa.Integer(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('anime_type', sa.String(length=20), nullable=True),
    sa.Column('anime_status', sa.String(length=30), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('studios', sa.Text(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mal_score', sa.Float(), nullable=True),
    sa.Column('mal_members', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anime_list_id'], ['anime_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_entries_anime_list_id'), 'anime_entries', ['anime_list_id'], unique=False)
    op.create_index(op.f('ix_anime_entries_mal_anime_id'), 'anime_entries', ['mal_anime_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anime_entries_mal_anime_id'), table_name='anime_entries')
    op.drop_index(op.f('ix_anime_entries_anime_list_id'), table_name='anime_entries')
    op.drop_table('anime_entries')
    op.drop_index(op.f('ix_user_preference_profiles_user_id'), table_name='user_preference_profiles')
    op.drop_table('user_preference_profiles')
    op.drop_index(op.f('ix_anime_lists_user_id'), table_name='anime_lists')
    op.drop_index(op.f('ix_anime_lists_mal_username'), table_name='anime_lists')
    op.drop_table('anime_lists')
    # ### end Alembic commands ###
